[package]
name = "xoodoo"
version = "0.1.0"
authors = ["Steve <steve@307703.xyz>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sponge = { path = "../sponge" }
