
# cargo-vet audits file

[[audits.rand_core]]
who = "Steve <steve@307703.xyz>"
criteria = "safe-to-deploy"
version = "0.6.4"

[[audits.zeroize]]
who = "Steve <steve@307703.xyz>"
criteria = "safe-to-deploy"
version = "1.6.0"
